### ISSUE TITLE
mimeType issue

### ISSUE THREAD

**Issue by MadsHolten** [stardog-union/stardog.js#139]
I am having issues when specifying 'text/turtle' as mimeType when doing a graph load using `db.graph.doPut`. 

Error: ` error TS2345: Argument of type '"text/turtle"' is not assignable to parameter of type 'RdfMimeType'.`

When changing `contentType?: HTTP.RdfMimeType` to `contentType?: string` I have no problem and the data loads fine. I don't know if it's a problem with my Typescript version.

**Comment by jmrog** [comment]
The error you're seeing is due to the fact that `RdfMimeType` is an enum, not a string, and so 'text/turtle' is not a value of the right type. You _could_ use `HTTP.RdfMimeType.TURTLE` as the `contentType` argument passed to `db.graph.doPut`, but that would ultimately only satisfy the type checker at compile time (the `RdfMimeType` enum won't exist at runtime, since it's in a `.d.ts` file). For reasons like this -- see the related discussion here: https://lukasbehal.com/2017-05-22-enums-in-declaration-files/ -- we should probably change these types from enums to union types. I'll submit a PR to this effect that should resolve the issue, but I'm open to further discussion.

**Comment by MadsHolten** [comment]
It works now. Thank you!
