### ISSUE TITLE
Browserify CORS

### ISSUE THREAD

**Issue by x0r2** [stardog-union/stardog.js#43]
Hi. I found problem. I have project on node.js. I'am use browserify to run app in browser.
When I try to integrate stardog.js to my project, and run browserify, i get CORS error in browser.

In my app.js in browser this code returned 'true'!:

``` javascript
var isNode = (typeof exports !== "undefined" && typeof module !== "undefined" && module.exports);
```

If set isNode to FALSE, this worked for me. Is there no other way to check isNode? Sorry for my bad english.

**Comment by edgarRd** [comment]
Currently stardog.js does not support browserify, but it can be used directly on the browser without requiring to be processed by browserify.

The reason why the code you mention is returning true, is because browserify adds `exports` and `module` to the script so they are registered, which is what that line checks.

Don't use browserify and everything should work directly just including stardog.js as shown in [1].

You're welcome to submit a pull request adding support for browserify.

[1] https://github.com/Complexible/stardog.js/tree/develop/examples/browser-app

**Comment by arb** [comment]
@x0r2 we're currently working on a re-write of this library that will be compatible will all the latest front end tooling. Keep an eye on the "development" branch for more details!
